export const ADMIN_STARTED_SCENE = 'ADMIN_STARTED_SCENE';
export const ADMIN_AREAS_SCENE = 'ADMIN_AREAS_SCENE';
export const ADMIN_CHANNELS_SCENE = 'ADMIN_CHANNELS_SCENE';
export const USER_STARTED_SCENE = 'USER_STARTED_SCENE';